### ISSUE TITLE
【應該更名】repo名稱應該被更改

### ISSUE THREAD

**Issue by KageRyo** [DABRiXPERT/YLNRailwaySystemInfo#1]
YLNRailwaySystemInfo -> CodeRyoMCRailwaySysteminfo

**Comment by DABRiXPERT** [comment]
更改Repo名可能會導致原先網址無法正常使用
因此僅會更改內容而不會更改Repo名

然後改名要等到環狀線完工 而且我也不知道什麼時候會完工
